{"name": "Проверка создания курьера с повторяющимся логином", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <tests.test_create_courier_endpoint.TestCreateCourierEndpoint object at 0x0000020382D28DD0>\n\n    @allure.title('Проверка создания курьера с повторяющимся логином')\n    def test_create_two_same_courier(self):\n        body = Helper.create_new_courier()\n        InterfaceApi.create_courier_endpoint(body)\n        create_response = InterfaceApi.create_courier_endpoint(body)\n>       assert (create_response.status_code == 409 and create_response.json()['message'] ==\n                CreateCourier.TEXT_ERROR_CREATE_409)\nE       AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE        +  where 409 = <Response [409]>.status_code\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.)\n\ntests\\test_create_courier_endpoint.py:25: AssertionError"}, "start": 1725209574018, "stop": 1725209574184, "uuid": "6898033e-bcfc-4b38-98e2-b572f30d353b", "historyId": "6e24e29eb8fa763ff3213b522a486c09", "testCaseId": "6e24e29eb8fa763ff3213b522a486c09", "fullName": "tests.test_create_courier_endpoint.TestCreateCourierEndpoint#test_create_two_same_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier_endpoint"}, {"name": "subSuite", "value": "TestCreateCourierEndpoint"}, {"name": "host", "value": "DNn"}, {"name": "thread", "value": "17452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier_endpoint"}]}